### ISSUE TITLE
Tags added to M&M stock are not displayed

### ISSUE THREAD

**Issue by intex0075** [amit0rana/betterOptionsTrading#19]
By default M&M is tagged under "Sell on Profit" tag. But, when the tag is selected from the drop down the stock is not listed.

Also, whenever any new tag is added to M&M
1. The tag gets added to Drop Down but not getting displayed next to the stock name
2. Unable to delete the tag

**Comment by amit0rana** [comment]
& is the culprit as its also a special character. I will look at it and release a fix

**Comment by intex0075** [comment]
Hi Amit,
Thanks for the prompt response - any tentative SLA for the fix?

**Comment by amit0rana** [comment]
Fixed in v 3.28. You can take the latest.
