### ISSUE TITLE
PL in Upstox

### ISSUE THREAD

**Issue by rapbhan** [amit0rana/betterOptionsTrading#2]
Hi there,

Thank you so much for this tool. May I please request a feature for Upstox?

Can you please have the Overall P&L for all the position(s) that one would hold? I knew you can filter it by strategy/watchlist. However, it would be great if you can show the overall P&L for all the positions next to the Day P&L as shown in the below image and preferably live P&L like one in Kite

![pnl](https://user-images.githubusercontent.com/46487/96544930-1bd91180-12c5-11eb-9d15-0852bf4a585a.png)

Thank you for the consideration!

Paddy

**Comment by amit0rana** [comment]
Hi Paddy,

 I closed all positions at upstox and withdrew all funds as I was finding its UX unfriendly so I do not have any account to test. This will take little time I will reactivate the account and work on it.

**Comment by amit0rana** [comment]
Not supporting upstox anymore.
