### ISSUE TITLE
Auto SL order is not showing Trail and Save Profit options

### ISSUE THREAD

**Issue by sidonkar** [amit0rana/betterOptionsTrading#23]
Whenever Auto SL order is placed, it places a SL limit order with the right price. However I do not see the buttons to trail or save profit. Is there any other option other than Auto SL to be enabled for this to work? Can you add a video or GIF for this to simplify the steps if I am missing something?
Many Thanks in advance.

**Comment by amit0rana** [comment]
I just tested is working fine. May have been some issue earlier. Please reopen if it still doesn't work for you.
