### ISSUE TITLE
BetterKite not working in Zerodha 22NOV

### ISSUE THREAD

**Issue by travick** [amit0rana/betterOptionsTrading#25]
Hi,

Till yest BetterKite was fine but looks like something in Zerodha code or Tampermonkey must have changed and BetterKite is not working. No UI elements shown excepts the Filter in the positions tab.

MS Edge on Win 11 did update yesterday but i dont quite remember. Inside tampermonkey, there are quite a few warnings in the userscript too.

If its known to many users then i can skip the detailed test. Just wanted to know if its working for others on win11, MS Edge latest, TM  4.16.1

Edit:
Checked i google Chrome, and it is working.
Looks like something in Edge / TM must have broken it.

**Comment by amit0rana** [comment]
Please mention the version number you are using. Upgrade to latest 3.55 and report if problem still exists.

**Comment by travick** [comment]
Edit:
Checked i google Chrome, and it is working.
Looks like something in Edge / TM must have broken it.

**Comment by travick** [comment]
3.56 now working in both MS Edge / Chrome.

Thank you, Amit.

**Comment by amit0rana** [comment]
Please update to 3.57, some bugs are fixed.
