### ISSUE TITLE
Premium Recvd Is not displayed

### ISSUE THREAD

**Issue by veresh** [amit0rana/betterOptionsTrading#26]
For the last few days the Premium Recvd Is not displayed in the order window, it was a helpful feature.
It used to show at the bottom left, just below the margin.

Please enable the same.

![image](https://user-images.githubusercontent.com/194953/212365009-5a65a5a3-b990-46a4-b593-bb6be99bb0f4.png)

**Comment by amit0rana** [comment]
fixed in v3.7
