### ISSUE TITLE
Feature Request: Can an option be given to see running position P&L while on order tab in Zerodha

### ISSUE THREAD

**Issue by MurlidharPandey21** [amit0rana/betterOptionsTrading#29]
Sometimes when we take trade for scalping and want to monitor the running trades P&L while continuously working on trailing, its good that current position running P&L is shown in the same tab of order window... this will help to avoid switching tabs multiple times and help to trail in much efficient way

**Comment by amit0rana** [comment]
If we have the original buy / sell price on that page then we can otherwise not. We won't know at what price you sokd/purchased so can't display p&l

**Comment by MurlidharPandey21** [comment]
> If we have the original buy / sell price on that page then we can otherwise not. We won't know at what price you sokd/purchased so can't display p&l

We will have the last executed buy or sell order for which there is no corresponding sell or buy order and the LTP is also displayed,  so with some calculations, is it possible?

**Comment by amit0rana** [comment]
Yes but there is a possibility that there are multiple orders

**Comment by amit0rana** [comment]
Technically not possible given the current constraints.
