### ISSUE TITLE
Margin field for each item under the positions

### ISSUE THREAD

**Issue by rbcdev** [amit0rana/betterOptionsTrading#3]
@amit0rana thanks for this excellent tool. would it be possible to enhance **betterKite** with a Margin column for each item in the positions section? Combined Margin at the header & footer (when positions are selected) also would be very helpful.

Thanks for reading the request!!

**Comment by amit0rana** [comment]
This is an excellent feature, even I want it but there is no easy way to calculate how much margin a particular position utilizes.

**Comment by rbcdev** [comment]
I have enhanced your tool to fetch the margin.

![image](https://user-images.githubusercontent.com/64958793/109992497-55209400-7d31-11eb-8a7d-e084482c9cc7.png)

I might need your support to add the margin value as a new column.

**Comment by amit0rana** [comment]
Nice. 
Do you recalculate new margin keeping 'margin benefit' in mind? For eg if you select PE margin would be 1.7, only CE margin would be 1.4 but when you select both PE and CE margin would be 1.9only.

Given that most of the times we are interested combined margin, it would make sense to show it at the bottom where you are showing now. Individual margin is not very helpful, moreover adding a column is lot more coding :)

**Comment by rbcdev** [comment]
Yes, I do(rather the API I am using) re-calculate margin keeping margin benefit. Examples below:

**Only PE**
![image](https://user-images.githubusercontent.com/64958793/113386112-24bb2c80-93a7-11eb-9c61-585ee37a3a92.png)

**Once CE**
![image](https://user-images.githubusercontent.com/64958793/113386137-356ba280-93a7-11eb-86a0-30cecc01fdba.png)

**PE & CE combined**
![image](https://user-images.githubusercontent.com/64958793/113386158-3ef50a80-93a7-11eb-8fae-df22d1cafe2c.png)

**Comment by rbcdev** [comment]
Agree with you on the additional effort required to add a margin column. I will see if I can add that later when I have more time.

**Comment by rbcdev** [comment]
code changes are published part of [PR#4](https://github.com/amit0rana/betterOptionsTrading/pull/4)
