### ISSUE TITLE
Premium Recvd label not visible on order window (Regular order tab)

### ISSUE THREAD

**Issue by yrbhan** [amit0rana/betterOptionsTrading#35]
The premium recvd lable is not visible on the Regular order tab in the Order window for buy/sell orders. 

Order window screenshot:
<img width="607" alt="Screenshot 2024-03-07 at 6 22 27 PM" src="https://github.com/amit0rana/betterOptionsTrading/assets/17044579/a5f541c1-0d76-41b3-b430-786b87964dd9">

Expected order window screeen with premium recvd label:
<img width="519" alt="Screenshot 2024-03-07 at 6 18 06 PM" src="https://github.com/amit0rana/betterOptionsTrading/assets/17044579/c4c21c14-6a3d-4123-a2be-fcf1acfaca8c">

P.S. This maybe due to layout changes with the addition of the Quick Orders tab.

**Comment by amit0rana** [comment]
This feature will only work for Nifty, BankNifty, Finnifty. I have intentionally not enabled it for other symbols

**Comment by yrbhan** [comment]
I guess it is not working for BankNifty too:

![Screenshot 2024-03-08 at 5 26 21 PM](https://github.com/amit0rana/betterOptionsTrading/assets/17044579/d90ae1e1-60c5-4866-9148-51a5858c0028)

**Comment by yrbhan** [comment]
Im using the version: 3.97

<img width="289" alt="Screenshot 2024-03-09 at 9 20 28 AM" src="https://github.com/amit0rana/betterOptionsTrading/assets/17044579/3fb6200e-dd9f-482d-909f-788656f054be">

**Comment by amit0rana** [comment]
I am not able to replicate. Which browser you are using? What is the version of tampermonkey?
Have you done any changes to the code? If you notice my 'settings' screenshot, there are lot more options than what you get in yours.

**Comment by yrbhan** [comment]
I am using brave browser: [Version 1.63.169 Chromium: 122.0.6261.111 (Official Build) (x86_64)]
Tampermonkey version: 5.0.1

I haven't made any changes to the code, it is strange why I am not able to see the other options shown in your 'settings' screenshot.

I just tried on chrome as well, it is the same behaviour.

**Comment by amit0rana** [comment]
Are you still facing the same problem? Some of the features I coded long time back so I forgot that there is a pro-mode, and you are not in pro-mode thats why your menu items are less. That shouldn't affect your usage.
Which OS are you trying on? Whats the resolution you are trying on? Is it possible to try on a browser where you can reset cache/cookies?
