### ISSUE TITLE
Filters on the positions tab are not working since last 3-4 sessions. 

### ISSUE THREAD

**Issue by smitnk1973** [amit0rana/betterOptionsTrading#37]
It seems Zerodha has done some changes to the kite page and the positions filter (script and expiry) is no longer visible.

**Comment by shrrao** [comment]
Also, the MTM of positions in the page/tab title also is not getting updated.

**Comment by amit0rana** [comment]
Please check latest v3.99 and reopen the ticket if still doesn't work

**Comment by smitnk1973** [comment]
Thanks, it is working now.
