### ISSUE TITLE
With latest changes pulled in, Ajax is facing error for automatically adding strikes, can you elaborate on the inputs required? API and non API way both not working

### ISSUE THREAD

**Issue by sidonkar** [amit0rana/betterOptionsTrading#39]

**Comment by sidonkar** [comment]
Request fails with {"status": "error","message": "Bad Request","error_type": "InputException"}
400 Bad Request

enctoken is working for SL trail and save profits

**Comment by amit0rana** [comment]
Hi Onkar, are you referring the new feature which lets you add ATM+- n strikes in the watchlist?

**Comment by sidonkar** [comment]
yes @amit0rana  i am talking about the same

**Comment by amit0rana** [comment]
Which version are you using? Works fine with 4.07

**Comment by sidonkar** [comment]
I merged 4.07 into my fork, i have my own changes too but facing problems, Following is merge link https://github.com/amit0rana/betterOptionsTrading/commit/312bb3f3358a3348dbc5e1e13872513598721634
I will double check my work once and if i am at fault will close this in 2 days.
BTW thank you very much for the script, much respect ! do check out my fork if u find anything interesting 
https://github.com/sidonkar/betterOptionsTrading

**Comment by amit0rana** [comment]
Just fyi, many apis have stopped working without the api key, even this feature 'OC' (short for option chain) only works with api key.

**Comment by sidonkar** [comment]
I tried with api key too but that did not work, i had one system in place via the sensibull option chain which i have checked in on my fork, please check if you find it usefull, its much more user friendly i feel and wont require api key !

**Comment by amit0rana** [comment]
For api key you need to generate token first. I have not added token generation code to this repo.

I checked your repo today, and I am taking in some good features. Will do it today once I go through sensibull feature as well.

Thanks for adding new features.

**Comment by sidonkar** [comment]
the api and token part are still not working for me, for some reason they dont work, i have paid api subscription and i have an app created too

**Comment by amit0rana** [comment]
Have you enabled CORS?

What error do you get?

I used CORS Everywhere extension to enable CORS

**Comment by sidonkar** [comment]
i have not enabled CORS, i get no error, it silently fails,

**Comment by amit0rana** [comment]
You have to enable CORS, without that api requests cannot be made. They will fail.

**Comment by amit0rana** [comment]
There is also a settings which you have to enable to use api. Its a checkbox.
