### ISSUE TITLE
Issue with Override freeze quantity

### ISSUE THREAD

**Issue by saswatmishra23** [amit0rana/betterOptionsTrading#40]
![Screenshot 2024-09-10 100954](https://github.com/user-attachments/assets/e9ce03a0-6208-4908-8468-672f7cb2f18b)

After checking on the Override quantity freeze, that dialog box comes each time from zerodha. Can you look into it and do something ?!

**Comment by amit0rana** [comment]
I am not able to replicate this. Can you confirm which browser and which betteKite version are you using?

**Comment by saswatmishra23** [comment]
I'm using betterKite 4.11 in chrome

**Comment by amit0rana** [comment]
go to settings and then uncheck "Warning when removing Qty Freeze".

betterKite intentionally gives warning to make sure user know what they are doing, you can disable that warning.
