### ISSUE TITLE
The position drop-down filtering the underlying derivative is broken. 

### ISSUE THREAD

**Issue by smitnk1973** [amit0rana/betterOptionsTrading#43]
The position drop-down filtering the underlying derivative is broken. This is probably due to the new updates to Kite page, where the context menu for position is now moved to end of the table. Please refer: https://support.zerodha.com/category/trading-and-markets/kite-web-and-mobile/others/articles/kite-positions-update

**Comment by amit0rana** [comment]
fixed. take latest 4.13
I have just fixed filtering for now, not sure what other things have also broken :) will do full check later.

**Comment by sidonkar** [comment]
The issue seems to be derived from the statement GM_getValue(GMPositionsName, defaultPositions); where positions are not getting returned.

**Comment by amit0rana** [comment]
No, the issue was change in html dom.

**Comment by smitnk1973** [comment]
Thanks. The filtering is fixed post update.
