### ISSUE TITLE
The plugin has stopped working today, i.e. 30-Oct-2024

### ISSUE THREAD

**Issue by smitnk1973** [amit0rana/betterOptionsTrading#46]
1) Error
Uncaught (in promise) ReferenceError: can't access lexical declaration 'D_LEVEL' before initialization
    init moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:2340
    GM_configInit moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:210
    read moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:482
    read moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:484
    GM_configInit moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:172
    construct moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:220
    config moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:582
    initGM moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:2087
    window["__f__m2vl0wrh.io"]/< moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:2063
    Pt https://kite.zerodha.com/positions:10
    window["__f__m2vl0wrh.io"]/< moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:1
    "__f__m2vl0wrh.io" moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:1
    Pt https://kite.zerodha.com/positions:10
    r https://kite.zerodha.com/positions:85
    <anonymous> https://kite.zerodha.com/positions:88
    _ https://kite.zerodha.com/positions:22
positions line 10 > injectedScript:2340:29

2) Error 2
GM_config failed to read saved settings! [betterKite.user.js:481:16](moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0)
Uncaught (in promise) ReferenceError: can't access lexical declaration 'D_LEVEL' before initialization
    init moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:2340
    GM_configInit moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:210
    read moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0:482

3) Error 3
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://6ddef9ee-ee7c-4f1c-b087-14c7b41d6271/userscripts/betterKite.user.js?id=94dad96f-3cfc-4de9-913f-0925eeb13ef0
Source Map URL: /sm/e1ebbfe1bf0b0061f0726ebc83434e1c2f8308e6354c415fd05ecccdaad47617.map//

**Comment by amit0rana** [comment]
try v4.18

**Comment by smitnk1973** [comment]
Thanks !
