### ISSUE TITLE
Not able to apply any Filer which contains & in their script Name for example L&TFinance , M&M , M&M Finance

### ISSUE THREAD

**Issue by PawanShukla** [amit0rana/betterOptionsTrading#7]
I guess some special handling is required while applying the tag with script name contains & in between

**Comment by amit0rana** [comment]
Yes we have to mention &amp; so for M&M we have to write M&amp;M

**Comment by PawanShukla** [comment]
do you mean i have to manually do it in script

**Comment by PawanShukla** [comment]
I want to show sorted label in dropdown is their a way i can open the saved file or DB in which newly created label and applied stock exist so that i can manipulate it as per my need ?

**Comment by amit0rana** [comment]
> do you mean i have to manually do it in script

Yes have to do manually but not in the script. Like I said before I have spent very little time on the holdings section :)

Click on tampermonkey icon -> click on 'set holdings' copy wheterver you see there, edit, paste it back and save

**Comment by amit0rana** [comment]
> I want to show sorted label in dropdown is their a way i can open the saved file or DB in which newly created label and applied stock exist so that i can manipulate it as per my need ?

yes, I just explained above how to do it.

**Comment by amit0rana** [comment]
Forgot to mention, you have to first enable 'pro mode' from settings. Once you enable pro mode then you will see 'set holdings'
