### ISSUE TITLE
Page reload on applying the tag on Any script

### ISSUE THREAD

**Issue by pawan-shukla** [amit0rana/betterOptionsTrading#8]
Its a big issue as suppose i have to apply 4 label on a script i have to take 8 action for that (Just double ) every time when you apply label page reload happens and script filtering disabled you need to enable it first by clicking on Holding/Position then apply one more tag and this need to be repeated for every label which is very painfull.

It will be a great favor if you can fix this asap.

**Comment by amit0rana** [comment]
Fixed it for positions. Yet to do for holdings

**Comment by intex0075** [comment]
Hi Amit, it would be very convenient - if you can fix this reload issue on holdings page as well. We not to change tags often - however, if we reset the plugin or switch to different system; it is a big one time task

**Comment by amit0rana** [comment]
You can copy paste your holdings easily. 

go to settings -> enabled 'pro mode'. Then on the menu go to 'set holdings'. Copy JSON from there and paste it in new sytem.
